### ISSUE TITLE
apply-hunk calls cleanup-semantic.shift-lossless with only one argument

### ISSUE THREAD

**Issue by Yehouda** [agrostis/diff-match-patch#2]
The function **apply-hunk** is calling the function **cleanup-semantic.shift-lossless** with only one argument, missing the test argument.

**Comment by agrostis** [comment]
Thanks a lot for reporting this. I fixed the issue, but would you mind attaching a use case where it comes up, so that I could include it in the tests?

**Comment by Yehouda** [comment]
The test **apply-patch** actually does the wrong call, but in this call it apparently doesn't use the **test** argument. Because the file cleanup.lisp is compiled with (saftey 0), **cleanup-semantic.shift-lossless** doesn't actually check if it got all the arguments. So you actually get a problem only if the mis-call affects the first argument. 

That doesn't happen on most implementatons, where the first argument always goes into the first argument register, but it does happen on LispWorks 32bit on x86 (Windows/MacOS/Linux/FreeBSD). so LispWorks 32 bit x86, the **apply-patch** fails with various errors. That is how I found it.

It will fail on other implementations if the wrong call actually use the test, but apparently none of the tests does that. I didn't got deep enough into the code to figure out how to cause such call. 

The proper way of catching such bugs is to compile the whole system with (safety 3) and (debug 3), and then run the tests. Also the compiler (at least on LispWorks) warns about it, so eliminating all compilation warnings would catch these bugs too.

**Comment by agrostis** [comment]
Fixed; tested with `(safety 3)` optimizations. Guess I'll have to do some further work on optimizations in this software.
