### ISSUE TITLE
The function join may apply with too many arguments

### ISSUE THREAD

**Issue by Yehouda** [agrostis/diff-match-patch#3]
The function **join** does apply #'concatenate on its argument (after removing empty elements), which may end up trying to call concatenate with too many arguments (more than **call-arguments-limit**). 

In the tests, in the **diff-timeout** test it ends up calling it with 4096 arguments, which at least on LispWorks is bigger than **call-arguments-limit** (2047). Since the file is compiled with safety 0, it may not give an error, but may crash badly as a result.

**Comment by agrostis** [comment]
Implemented this as an iteration on elements inside an iteration on parts. The following works (e. g. in SBCL 2.0.1 on Linux), while previously it produced a memory fault:

```
(time
  (flet ((rstr ()
            (make-string (+ (random 50) 50)
              :initial-element (code-char (+ 32 (random 96))))))
     (let ((parts (loop repeat 100000 collect (rstr))))
       (length (dmp::join parts))))
)

Evaluation took:
  1.164 seconds of real time
  1.156480 seconds of total run time (1.007044 user, 0.149436 system)
  [ Run times consist of 0.497 seconds GC time, and 0.660 seconds non-GC time. ]
  99.31% CPU
  1,277,982,820 processor cycles
  184,683,008 bytes consed
  
⇒ 7452443

```

**Comment by Yehouda** [comment]
Should add it to the test, no?

**Comment by agrostis** [comment]
I considered it, but ultimately decided against, because `join` is just an auxiliary function, and unit tests should rather be focused on the subject matter of the software.
